# Generated by Django 6.0.4 on 2026-04-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_productsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
