# Generated by Django 6.0.4 on 2026-04-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workinghour_break_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Aguardando confirmação'), ('confirmed', 'Confirmado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado'), ('no_show', 'Não compareceu')], default='confirmed', max_length=20),
        ),
    ]
